name: Lint & Test

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    container:
      image: golang:1.19.1

    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.19.1

    steps:
      - uses: actions/checkout@v2
      - run: go test ./... -race
