name: Lint & Test

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    container:
      image: golang:1.20

    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.20

    steps:
      - uses: actions/checkout@v2
      - run: go test ./... -race -coverprofile=coverage.txt -covermode=atomic
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

